/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as AdminToursRouteImport } from './routes/_admin/tours'
import { Route as AdminTourFeaturesRouteImport } from './routes/_admin/tour-features'
import { Route as AdminSupportRouteImport } from './routes/_admin/support'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminCountriesRouteImport } from './routes/_admin/countries'
import { Route as AdminCitiesRouteImport } from './routes/_admin/cities'
import { Route as AdminAgenciesRouteImport } from './routes/_admin/agencies'
import { Route as AdminTourfeaturePageRouteImport } from './routes/_admin/tourfeature/page'
import { Route as AdminCountriesCountriesRouteImport } from './routes/_admin/countries/countries'
import { Route as AdminCityPageRouteImport } from './routes/_admin/city/page'
import { Route as AdminCityComponentsCityDeleteDialogRouteImport } from './routes/_admin/city/components/CityDeleteDialog'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminToursRoute = AdminToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTourFeaturesRoute = AdminTourFeaturesRouteImport.update({
  id: '/tour-features',
  path: '/tour-features',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCountriesRoute = AdminCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/cities',
  path: '/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgenciesRoute = AdminAgenciesRouteImport.update({
  id: '/agencies',
  path: '/agencies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTourfeaturePageRoute = AdminTourfeaturePageRouteImport.update({
  id: '/tourfeature/page',
  path: '/tourfeature/page',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCountriesCountriesRoute = AdminCountriesCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => AdminCountriesRoute,
} as any)
const AdminCityPageRoute = AdminCityPageRouteImport.update({
  id: '/city/page',
  path: '/city/page',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCityComponentsCityDeleteDialogRoute =
  AdminCityComponentsCityDeleteDialogRouteImport.update({
    id: '/city/components/CityDeleteDialog',
    path: '/city/components/CityDeleteDialog',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/agencies': typeof AdminAgenciesRoute
  '/cities': typeof AdminCitiesRoute
  '/countries': typeof AdminCountriesRouteWithChildren
  '/settings': typeof AdminSettingsRoute
  '/support': typeof AdminSupportRoute
  '/tour-features': typeof AdminTourFeaturesRoute
  '/tours': typeof AdminToursRoute
  '/users': typeof AdminUsersRoute
  '/city/page': typeof AdminCityPageRoute
  '/countries/countries': typeof AdminCountriesCountriesRoute
  '/tourfeature/page': typeof AdminTourfeaturePageRoute
  '/city/components/CityDeleteDialog': typeof AdminCityComponentsCityDeleteDialogRoute
}
export interface FileRoutesByTo {
  '/agencies': typeof AdminAgenciesRoute
  '/cities': typeof AdminCitiesRoute
  '/countries': typeof AdminCountriesRouteWithChildren
  '/settings': typeof AdminSettingsRoute
  '/support': typeof AdminSupportRoute
  '/tour-features': typeof AdminTourFeaturesRoute
  '/tours': typeof AdminToursRoute
  '/users': typeof AdminUsersRoute
  '/': typeof AdminIndexRoute
  '/city/page': typeof AdminCityPageRoute
  '/countries/countries': typeof AdminCountriesCountriesRoute
  '/tourfeature/page': typeof AdminTourfeaturePageRoute
  '/city/components/CityDeleteDialog': typeof AdminCityComponentsCityDeleteDialogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/agencies': typeof AdminAgenciesRoute
  '/_admin/cities': typeof AdminCitiesRoute
  '/_admin/countries': typeof AdminCountriesRouteWithChildren
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/support': typeof AdminSupportRoute
  '/_admin/tour-features': typeof AdminTourFeaturesRoute
  '/_admin/tours': typeof AdminToursRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/city/page': typeof AdminCityPageRoute
  '/_admin/countries/countries': typeof AdminCountriesCountriesRoute
  '/_admin/tourfeature/page': typeof AdminTourfeaturePageRoute
  '/_admin/city/components/CityDeleteDialog': typeof AdminCityComponentsCityDeleteDialogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agencies'
    | '/cities'
    | '/countries'
    | '/settings'
    | '/support'
    | '/tour-features'
    | '/tours'
    | '/users'
    | '/city/page'
    | '/countries/countries'
    | '/tourfeature/page'
    | '/city/components/CityDeleteDialog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/agencies'
    | '/cities'
    | '/countries'
    | '/settings'
    | '/support'
    | '/tour-features'
    | '/tours'
    | '/users'
    | '/'
    | '/city/page'
    | '/countries/countries'
    | '/tourfeature/page'
    | '/city/components/CityDeleteDialog'
  id:
    | '__root__'
    | '/_admin'
    | '/_admin/agencies'
    | '/_admin/cities'
    | '/_admin/countries'
    | '/_admin/settings'
    | '/_admin/support'
    | '/_admin/tour-features'
    | '/_admin/tours'
    | '/_admin/users'
    | '/_admin/'
    | '/_admin/city/page'
    | '/_admin/countries/countries'
    | '/_admin/tourfeature/page'
    | '/_admin/city/components/CityDeleteDialog'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tours': {
      id: '/_admin/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof AdminToursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tour-features': {
      id: '/_admin/tour-features'
      path: '/tour-features'
      fullPath: '/tour-features'
      preLoaderRoute: typeof AdminTourFeaturesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/support': {
      id: '/_admin/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/countries': {
      id: '/_admin/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof AdminCountriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cities': {
      id: '/_admin/cities'
      path: '/cities'
      fullPath: '/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/agencies': {
      id: '/_admin/agencies'
      path: '/agencies'
      fullPath: '/agencies'
      preLoaderRoute: typeof AdminAgenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tourfeature/page': {
      id: '/_admin/tourfeature/page'
      path: '/tourfeature/page'
      fullPath: '/tourfeature/page'
      preLoaderRoute: typeof AdminTourfeaturePageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/countries/countries': {
      id: '/_admin/countries/countries'
      path: '/countries'
      fullPath: '/countries/countries'
      preLoaderRoute: typeof AdminCountriesCountriesRouteImport
      parentRoute: typeof AdminCountriesRoute
    }
    '/_admin/city/page': {
      id: '/_admin/city/page'
      path: '/city/page'
      fullPath: '/city/page'
      preLoaderRoute: typeof AdminCityPageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/city/components/CityDeleteDialog': {
      id: '/_admin/city/components/CityDeleteDialog'
      path: '/city/components/CityDeleteDialog'
      fullPath: '/city/components/CityDeleteDialog'
      preLoaderRoute: typeof AdminCityComponentsCityDeleteDialogRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminCountriesRouteChildren {
  AdminCountriesCountriesRoute: typeof AdminCountriesCountriesRoute
}

const AdminCountriesRouteChildren: AdminCountriesRouteChildren = {
  AdminCountriesCountriesRoute: AdminCountriesCountriesRoute,
}

const AdminCountriesRouteWithChildren = AdminCountriesRoute._addFileChildren(
  AdminCountriesRouteChildren,
)

interface AdminRouteChildren {
  AdminAgenciesRoute: typeof AdminAgenciesRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminCountriesRoute: typeof AdminCountriesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTourFeaturesRoute: typeof AdminTourFeaturesRoute
  AdminToursRoute: typeof AdminToursRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCityPageRoute: typeof AdminCityPageRoute
  AdminTourfeaturePageRoute: typeof AdminTourfeaturePageRoute
  AdminCityComponentsCityDeleteDialogRoute: typeof AdminCityComponentsCityDeleteDialogRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgenciesRoute: AdminAgenciesRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminCountriesRoute: AdminCountriesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTourFeaturesRoute: AdminTourFeaturesRoute,
  AdminToursRoute: AdminToursRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCityPageRoute: AdminCityPageRoute,
  AdminTourfeaturePageRoute: AdminTourfeaturePageRoute,
  AdminCityComponentsCityDeleteDialogRoute:
    AdminCityComponentsCityDeleteDialogRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
